#!/bin/bash
mkdir -pv /mnt/Movies
mkdir -pv /mnt/TV
mkdir -pv /mnt/plexconfig

sudo docker create \
  --name=plex \
  --net=host \
  -e PUID=1000 \
  -e PGID=1000 \
  -e VERSION=docker \
  -v /mnt/plexconfig:/config \
  -v /mnt/TV/tv:/tv \
  -v /mnt/Movies:/movies \
  --restart unless-stopped \
  linuxserver/plex

sudo docker start plex
